module Ignite
  TYPE_BYTE = 1
  TYPE_SHORT = 2
  TYPE_INT = 3
  TYPE_LONG = 4
  TYPE_FLOAT = 5
  TYPE_DOUBLE = 6
  TYPE_CHAR = 7
  TYPE_BOOL = 8
  TYPE_STRING = 9
  TYPE_UUID = 10
  TYPE_DATE = 11

  TYPE_BYTE_ARRAY = 12
  TYPE_INT_ARRAY = 14
  TYPE_LONG_ARRAY = 15
  TYPE_FLOAT_ARRAY = 16
  TYPE_DOUBLE_ARRAY = 17
  TYPE_CHAR_ARRAY = 18
  TYPE_BOOL_ARRAY = 19

  TYPE_ENUM = 28
  TYPE_DECIMAL = 30
  TYPE_TIMESTAMP = 33
  TYPE_TIME = 36

  TYPE_NULL = 101
end
