name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 3.0
          config: example-ignite.xml
        - ruby: 2.7
          config: authentication.xml
          env: IGNITE_AUTH=t
    env:
      IGNITE_VERSION: 2.9.1
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - uses: actions/cache@v2
      with:
        path: ~/ignite
        key: ignite-${{ env.IGNITE_VERSION }}
      id: cache-ignite
    - name: Download Ignite
      if: steps.cache-ignite.outputs.cache-hit != 'true'
      run: |
        wget -q https://apache.osuosl.org//ignite/$IGNITE_VERSION/apache-ignite-$IGNITE_VERSION-bin.zip
        unzip -q apache-ignite-$IGNITE_VERSION-bin.zip
        mv apache-ignite-$IGNITE_VERSION-bin ~/ignite

    - run: |
        cp test/support/authentication.xml ~/ignite/examples/config
        ~/ignite/bin/ignite.sh ~/ignite/examples/config/${{ matrix.config }} &
        sleep 15
        ~/ignite/bin/control.sh --user ignite --password ignite --set-state ACTIVE --yes
    - run: ${{ matrix.env }} bundle exec rake test
